### ISSUE TITLE
Custom Shader batch draw needs refine

### ISSUE THREAD

**Issue by halx99** [c4games/cocos-re#245]
RT
see also: https://github.com/c4games/cocos-re/issues/234

**Comment by etsek** [comment]
This issue is not specific to Spine nodes, here's how sprites look in Material System test (cpp-tests).
 
![cpp-tests_material_system](https://user-images.githubusercontent.com/72875980/96916387-2c011480-14b0-11eb-92db-ff387312702b.png)
